### ISSUE TITLE
HashMap初始入参

### ISSUE THREAD

**Issue by xubaolei** [newbee-ltd/newbee-mall-api#11]
ltd.newbee.mall.api.NewBeeMallGoodsAPI#search   
--Map params = new HashMap(4);

最大params是6，初始化大小设置为8是不是好点？
设置为4，*0.75的话，设置到第四个就会开始走扩容了
设置为8，*0.75的话，设置到第六个也不会扩容

**Comment by ZHENFENG13** [comment]
嗯，感谢建议。
