### ISSUE TITLE
账号管理保存功能将用户密码修改为空字符串，导致用户无法登录

### ISSUE THREAD

**Issue by NaNrailgun** [newbee-ltd/newbee-mall-api#2]
开源作者：

​		您好，首先非常感谢您能将新蜂商城系统开源，该开源项目使我受益匪浅。

​		之后，我在学习该项目的过程中发现了一个小bug，bug情况如下：

1. 我在系统中注册了一个user账号，密码为123456

![image-20200727171329175](https://user-images.githubusercontent.com/50312470/88530021-5b2ff300-d033-11ea-9b64-327a0e93bc96.png)

2.当我使用账号管理修改相关信息时，因不想修改密码的缘故没有填写“修改密码”选项
![image-20200727171447503](https://user-images.githubusercontent.com/50312470/88530082-6aaf3c00-d033-11ea-88f0-a4593281b224.png)
3.进行保存 
![image-20200727171458532](https://user-images.githubusercontent.com/50312470/88530110-74d13a80-d033-11ea-9bb7-7dc1bca88a27.png)
4.此时的后端调试结果如下，前端将空字符串传至/user/info接口，使得将空字符串（d41d8cd98f00b204e9800998ecf8427e）作为密码写入数据库，最终导致用户无法登录的情况
![image-20200727171524993](https://user-images.githubusercontent.com/50312470/88530139-7dc20c00-d033-11ea-8ff8-9651f810dcde.png)
![image-20200727171724023](https://user-images.githubusercontent.com/50312470/88530159-87e40a80-d033-11ea-8e53-502caa1e922d.png)
我按照我自己的想法对项目代码做了修改，即在NewBeeMallUserServiceImpl中的updateUserInfo方法中增加了如下代码：

```java
    //若密码为空字符，则表明用户不打算修改密码，使用原密码保存
    if (!MD5Util.MD5Encode("", "UTF-8").equals(mallUser.getPasswordMd5())){
        user.setPasswordMd5(mallUser.getPasswordMd5());
    }
```
![image-20200727172205558](https://user-images.githubusercontent.com/50312470/88530219-a21de880-d033-11ea-8cfd-5a8f263bf9dd.png)
最终效果如下：

使得用户若未填写“修改密码”选项时，利用原密码进行保存，不修改原密码。
![image-20200727172448436](https://user-images.githubusercontent.com/50312470/88530249-ac3fe700-d033-11ea-82de-1ff9d6035502.png)
![image-20200727172505589](https://user-images.githubusercontent.com/50312470/88530281-bcf05d00-d033-11ea-8df5-246dbff5b46d.png)
****
以上就是关于这个小bug情况和解决这个小bug的过程，若对项目的理解不够透彻还请作者见谅。我已经开启了一个pull request。目前，我是一名大二学生，若您能接受此处pull request，那么它将可以出现在我未来春秋招的简历之中。我会非常感激您！

最后，再次感谢您能开源此项目。

**Comment by newbee-mall** [comment]
感谢！已合并。
