### ISSUE TITLE
vue页面cart.vue修正

### ISSUE THREAD

**Issue by weidongbcn** [newbee-ltd/newbee-mall-api#5]
很抱歉发在这里，因为你的vue那里不允许提交issues.

第114 这段修正:

async onChange(value, detail) {
      if (this.list.filter(item => item.CartItemId == detail.name)[0].GoodsCount == value) return
      Toast.loading({ message: '修改中...', forbidClick: true });
      const params = {
        cartItemId: detail.name,
        goodsCount: value
      }
      try {
      const { data } = await modifyCart(params)
      this.list.forEach(item => {
        if (item.CartItemId == detail.name) {
          item.GoodsCount = value
        }
      })
      } catch (e) {
      console.log( e.message );
      }
      Toast.clear();
    },

加了catch, 要不然浏览器中红叉叉难看

**Comment by newbee-mall** [comment]
好的，我检查一下。
