### ISSUE TITLE
更新库存返回结果与预期不一致

### ISSUE THREAD

**Issue by NaNrailgun** [newbee-ltd/newbee-mall-api#6]
开源作者，您好。
        当前项目中```NewBeeMallGoodsMapper#updateStockNum```方法在更新库存时，返回结果与预期不一致。
**当更新多个商品库存时若其中一个商品库存少于购买数时，也会返回1** 则无法根据返回值判断商品库存是否全部更新成功，可能会出现超卖问题。
        测试代码已上传至我的[fork仓库中](https://github.com/NaNrailgun/newbee-mall-api
)。
****
项目截图如下：
![10005库存为0](https://user-images.githubusercontent.com/50312470/96220964-50468800-0fbc-11eb-92f8-5a18785f3d1e.png)
![更新库存](https://user-images.githubusercontent.com/50312470/96220949-4a50a700-0fbc-11eb-84ca-1f8218788a09.png)
![返回值依旧为1](https://user-images.githubusercontent.com/50312470/96220994-5a688680-0fbc-11eb-86e9-f87c35e34f37.png)
![并发可能存在超卖问题](https://user-images.githubusercontent.com/50312470/96221202-b501e280-0fbc-11eb-8341-10717c4447bc.png)

**Comment by newbee-mall** [comment]
这个应该不是小于 1 ，应该改成小于当前 stockNumDTOs 列表的 size()，我回头改一下，感谢你的提醒。

**Comment by NaNrailgun** [comment]
> 这个应该不是小于 1 ，应该改成小于当前 stockNumDTOs 列表的 size()，我回头改一下，感谢你的提醒。

我曾尝试过这样改，但貌似也不符合预期，```NewBeeMallGoodsMapper#updateStockNum```当全部商品更新不成功时才会返回0，当其中任意一个商品库存更新成功就会返回1，没有其他返回值情况。

**Comment by newbee-mall** [comment]
已经有解决方案了，后续我会发布上来。

**Comment by NaNrailgun** [comment]
@newbee-mall 请问近期会有发布吗？如果方便的话可否将方案告诉我，我想试试
